// Daily newsletter / digest generator. Composes a markdown bulletin from
// every previewable tournament — top fits, key angle, weather. Output is
// safe to drop into Substack, Beehiiv, Discord, Slack, or send as email.
//
// The structure intentionally mirrors what an editor would write by hand,
// so a human can polish without rewriting from scratch.

import { buildPreviewAsync } from "@/lib/preview";
import { listPreviewable } from "@/lib/preview";

export type NewsletterSection = {
  tournament: string;
  course: string;
  headline: string;
  weather: string;
  topFits: { player: string; rationale: string; edge: number }[];
  primaryAngle: { title: string; body: string } | null;
};

export type Newsletter = {
  generatedAt: string;
  date: string;          // YYYY-MM-DD
  title: string;
  intro: string;
  sections: NewsletterSection[];
};

export async function buildDailyDigest(): Promise<Newsletter> {
  const items = listPreviewable();
  const sections: NewsletterSection[] = [];
  for (const item of items) {
    const preview = await buildPreviewAsync(item.slug);
    if (!preview) continue;
    sections.push({
      tournament: preview.tournament,
      course: preview.snapshot.name,
      headline: preview.headline,
      weather: preview.weather,
      topFits: preview.fitPlayers.slice(0, 3).map((f) => ({
        player: f.player.name,
        rationale: f.rationale,
        edge: f.windAdjusted,
      })),
      primaryAngle: preview.angles[0] ?? null,
    });
  }
  const today = new Date();
  const date = today.toISOString().slice(0, 10);
  return {
    generatedAt: today.toISOString(),
    date,
    title: `Greenside Daily — ${formatDate(today)}`,
    intro:
      sections.length === 1
        ? `One event on the board. Here's the one-screen read.`
        : `${sections.length} events on the board. Conditions, top fits, and one angle each — skim it in 90 seconds.`,
    sections,
  };
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });
}

// ── Renderers ─────────────────────────────────────────────────────

export function renderMarkdown(nl: Newsletter): string {
  const lines: string[] = [];
  lines.push(`# ${nl.title}`);
  lines.push("");
  lines.push(`*${nl.intro}*`);
  lines.push("");
  for (const s of nl.sections) {
    lines.push(`## ${s.tournament}`);
    lines.push(`**${s.course}** — *${s.headline}*`);
    lines.push("");
    lines.push(`**Conditions:** ${s.weather}`);
    lines.push("");
    lines.push(`**Top fits**`);
    for (const f of s.topFits) {
      const sign = f.edge >= 0 ? "+" : "";
      lines.push(`- **${f.player}** (${sign}${f.edge.toFixed(2)}u 4-rd edge) — ${f.rationale}`);
    }
    if (s.primaryAngle) {
      lines.push("");
      lines.push(`**Angle: ${s.primaryAngle.title}**`);
      lines.push(s.primaryAngle.body);
    }
    lines.push("");
    lines.push(`---`);
    lines.push("");
  }
  lines.push(
    `*Generated by Greenside. Wind-drag penalty uses the live forecast; coefficients are calibrated against recent rounds. Not investment advice.*`,
  );
  return lines.join("\n");
}

export function renderHtml(nl: Newsletter): string {
  // A simple, self-contained HTML rendering for email clients that don't
  // do markdown. Inline styles only; no external assets.
  const sections = nl.sections
    .map((s) => {
      const fits = s.topFits
        .map((f) => {
          const sign = f.edge >= 0 ? "+" : "";
          return `<li><strong>${escapeHtml(f.player)}</strong>
            <span style="color:#8ee68e">(${sign}${f.edge.toFixed(2)}u)</span>
            — ${escapeHtml(f.rationale)}</li>`;
        })
        .join("");
      const angle = s.primaryAngle
        ? `<p><strong>Angle: ${escapeHtml(s.primaryAngle.title)}</strong><br/>${escapeHtml(s.primaryAngle.body)}</p>`
        : "";
      return `
        <h2 style="margin-top:32px;font-family:Georgia,serif;font-style:italic">${escapeHtml(s.tournament)}</h2>
        <p style="color:#555"><strong>${escapeHtml(s.course)}</strong> — <em>${escapeHtml(s.headline)}</em></p>
        <p><strong>Conditions:</strong> ${escapeHtml(s.weather)}</p>
        <ul>${fits}</ul>
        ${angle}
        <hr style="border:0;border-top:1px solid #ddd;margin:24px 0"/>
      `;
    })
    .join("");
  return `<!doctype html><html><body style="font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#222;max-width:640px;margin:0 auto;padding:24px">
    <h1 style="font-family:Georgia,serif">${escapeHtml(nl.title)}</h1>
    <p style="color:#666;font-style:italic">${escapeHtml(nl.intro)}</p>
    ${sections}
    <p style="color:#888;font-size:12px;margin-top:32px">Generated by Greenside. Not investment advice.</p>
  </body></html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
